Alterado o nome do branch de "Development" para "develop"

diff --git a/.github/workflows/cd-release.yml b/.github/workflows/cd-release.yml
--- a/.github/workflows/cd-release.yml
+++ b/.github/workflows/cd-release.yml
@@ -28,12 +28,12 @@ jobs:
       - name: 01 - Checkout application
         uses: actions/checkout@v4
 
-      - name: 02 - Validate tag belongs to Development branch
+      - name: 02 - Validate tag belongs to develop branch
         run: |
-          git fetch origin Development
+          git fetch origin develop
 
-          if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/Development; then
-            echo "::error::The tag '$GITHUB_REF_NAME' is not on the Development branch."
+          if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/develop; then
+            echo "::error::The tag '$GITHUB_REF_NAME' is not on the develop branch."
             exit 1
           fi
 
